version: "3.8"

services:
  fastapi:
    build: .
    command:
      - bash
      - -c
      - >
        alembic upgrade head && 
        uvicorn src.core.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    env_file:
      - /.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - test_db

  db:
    image: postgres:14
    container_name: "db"
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  test_db:
    image: postgres:14
    container_name: "test_db"
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

volumes:
  postgres_data:
